[build]
target = "riscv64imac-unknown-none-elf"

[target.riscv64imac-unknown-none-elf]
rustflags = [
  "-C", "link-arg=-Tkernel.ld",
]

runner = """
  qemu-system-riscv64 \
    -M virt \
    -bios none \
    -nographic \
    -m 128M \
    -smp 1 \
    -kernel
"""

[term]
verbose = true
