[build]
target = "riscv64imac-unknown-none-elf"

[target.riscv64imac-unknown-none-elf]
rustflags = [
  "-C", "link-arg=-Tkernel.ld",
]

runner = """
  qemu-system-riscv64 \
    -M virt \
    -bios none \
    -nographic \
    -m 128M \
    -smp 3 \
    -drive file=fs.img,if=none,format=raw,id=x0 \
    -device virtio-blk-device,drive=x0,bus=virtio-mmio-bus.0 \
    -kernel
"""

[term]
verbose = true
